# Generated by Django 4.2.1 on 2023-09-27 07:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listing_comment_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2023, 9, 27, 7, 24, 52, 11227, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(blank=True, max_length=65),
        ),
        migrations.AlterField(
            model_name='listing',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2023, 9, 27, 7, 24, 52, 9619, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='listing',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
