# Generated by Django 4.2.1 on 2023-09-30 02:25

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_comment_created_at_alter_listing_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='interested_user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2023, 9, 30, 2, 25, 58, 535575, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='listing',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2023, 9, 30, 2, 25, 58, 533589, tzinfo=datetime.timezone.utc)),
        ),
    ]
