# Generated by Django 4.2.1 on 2023-10-04 07:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_listing_interested_user_alter_comment_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='is_win',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2023, 10, 4, 7, 0, 15, 331684, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='listing',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2023, 10, 4, 7, 0, 15, 329730, tzinfo=datetime.timezone.utc)),
        ),
    ]
