# Generated by Django 4.2.1 on 2024-02-04 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_remove_listing_interested_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='is_win',
        ),
    ]
